#!/usr/bin/env bash
# Interactive setup script for Ares Bib Logger.
# Prompts for configuration and writes a .env file.
# Re-running is non-destructive — existing values are shown as defaults.
set -euo pipefail

# Load existing .env so current values become defaults.
if [[ -f .env ]]; then
    # shellcheck disable=SC1091
    set +u
    source .env 2>/dev/null || true
    set -u
fi

# prompt VAR_NAME "Label" "default"  — reads input, falls back to default, sets variable.
prompt() {
    local -n _ref="$1"
    local label="$2" default="$3"
    printf "  %s [%s]: " "$label" "$default"
    read -r _input
    _ref="${_input:-$default}"
}

echo ""
echo "==========================================="
echo "  Ares Bib Logger — Setup"
echo "==========================================="
echo ""

# ── [1] Mesh technology ──────────────────────────────────────────────────────
echo "[1/5] Mesh technology"
echo "      1) Meshtastic (default)"
echo "      2) MeshCore"
printf "      Choice [1]: "
read -r _tech_choice
case "${_tech_choice:-1}" in
    2) MESH_TECHNOLOGY="meshcore" ;;
    *) MESH_TECHNOLOGY="meshtastic" ;;
esac
echo "      → ${MESH_TECHNOLOGY}"

# ── [2] Mesh-specific config ─────────────────────────────────────────────────
echo ""
if [[ "$MESH_TECHNOLOGY" == "meshcore" ]]; then
    echo "[2/5] MeshCore configuration"
    prompt MESHCORE_NODE_ADDRESS "MeshCore node address (host:port)" "${MESHCORE_NODE_ADDRESS:-192.168.1.50:5525}"
    prompt MESHCORE_CHANNEL_NAME "Channel name" "${MESHCORE_CHANNEL_NAME:-PUBLIC}"
    # Keep Meshtastic vars at their existing or default values (not prompted).
    MQTT_REGION="${MQTT_REGION:-US}"
    MQTT_CHANNEL_NUM="${MQTT_CHANNEL_NUM:-2}"
    MQTT_CHANNEL_NAME="${MQTT_CHANNEL_NAME:-LongFast}"
    MQTT_CHANNEL_INDEX="${MQTT_CHANNEL_INDEX:-0}"
    MQTT_GATEWAY_NODE_ID="${MQTT_GATEWAY_NODE_ID:-}"
    MQTT_NODE_LONG_NAME="${MQTT_NODE_LONG_NAME:-Auto Logger}"
    MQTT_NODE_SHORT_NAME="${MQTT_NODE_SHORT_NAME:-Log}"
else
    echo "[2/5] Meshtastic configuration"
    prompt MQTT_GATEWAY_NODE_ID "Gateway Node ID (hex, e.g. a3b4c5d6)" "${MQTT_GATEWAY_NODE_ID:-}"
    prompt MQTT_REGION          "Region" "${MQTT_REGION:-US}"
    prompt MQTT_CHANNEL_NUM     "Channel number" "${MQTT_CHANNEL_NUM:-2}"
    prompt MQTT_CHANNEL_NAME    "Channel name" "${MQTT_CHANNEL_NAME:-LongFast}"
    prompt MQTT_CHANNEL_INDEX   "Channel index (0–7)" "${MQTT_CHANNEL_INDEX:-0}"
    prompt MQTT_NODE_LONG_NAME  "Node long name (max 20 chars)" "${MQTT_NODE_LONG_NAME:-Auto Logger}"
    prompt MQTT_NODE_SHORT_NAME "Node short name (max 4 chars)" "${MQTT_NODE_SHORT_NAME:-Log}"
    MESHCORE_NODE_ADDRESS="${MESHCORE_NODE_ADDRESS:-}"
    MESHCORE_CHANNEL_NAME="${MESHCORE_CHANNEL_NAME:-PUBLIC}"
fi

# ── [3] MQTT broker ──────────────────────────────────────────────────────────
echo ""
echo "[3/5] MQTT broker"
prompt MQTT_PORT "Broker port" "${MQTT_PORT:-1883}"

# ── [4] Database ─────────────────────────────────────────────────────────────
echo ""
echo "[4/5] Database"
prompt DB_PASSWORD "Password" "${DB_PASSWORD:-postgres}"
prompt DB_NAME     "Name" "${DB_NAME:-ares_bib_logger}"
prompt DB_USER     "User" "${DB_USER:-postgres}"
prompt DB_PORT     "Port" "${DB_PORT:-5432}"

# ── [5] Application ──────────────────────────────────────────────────────────
echo ""
echo "[5/5] Application"
prompt SERVER_PORT "Server port" "${SERVER_PORT:-8080}"
prompt LOG_LEVEL   "Log level (debug/info/warn/error)" "${LOG_LEVEL:-info}"
prompt TIMEZONE    "Timezone (IANA name)" "${TIMEZONE:-America/New_York}"

# ── Write .env ───────────────────────────────────────────────────────────────
echo ""
printf "Writing .env... "

cat > .env << EOF
# Generated by scripts/setup.sh — re-run to update, or edit manually.

# Application
SERVER_PORT=${SERVER_PORT}
LOG_LEVEL=${LOG_LEVEL}
TIMEZONE=${TIMEZONE}

# Mesh — set MQTT_ENABLED=false to run in manual-entry-only mode
MQTT_ENABLED=true
MESH_TECHNOLOGY=${MESH_TECHNOLOGY}

# MQTT broker (shared for both Meshtastic and MeshCore)
MQTT_HOST=localhost
MQTT_PORT=${MQTT_PORT}

# Meshtastic-specific
MQTT_REGION=${MQTT_REGION}
MQTT_CHANNEL_NUM=${MQTT_CHANNEL_NUM}
MQTT_CHANNEL_NAME=${MQTT_CHANNEL_NAME}
MQTT_CHANNEL_INDEX=${MQTT_CHANNEL_INDEX}
MQTT_GATEWAY_NODE_ID=${MQTT_GATEWAY_NODE_ID}
MQTT_NODE_LONG_NAME=${MQTT_NODE_LONG_NAME}
MQTT_NODE_SHORT_NAME=${MQTT_NODE_SHORT_NAME}

# MeshCore-specific
MESHCORE_NODE_ADDRESS=${MESHCORE_NODE_ADDRESS}
MESHCORE_CHANNEL_NAME=${MESHCORE_CHANNEL_NAME}

# Database
DB_HOST=localhost
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_SSL_MODE=disable
EOF

echo "done."
echo ""
echo "Next steps:"
if [[ "$MESH_TECHNOLOGY" == "meshcore" ]]; then
    echo "  docker compose --profile meshcore up -d"
else
    echo "  docker compose up -d"
fi
echo ""
